site_name: openshift-ppc64le
site_url: http://openshift-ppc64le.readthedocs.io
theme:
  name: mkdocs
  nav_style: dark
  navigation_depth: 3
  favicon: img/favicon.ico
nav:
  - Home(grown): index.md
  - Contribute: contrib.md
  - External: actually-helped.md
copyright: © Copyright IBM Corp. 2020, 2021
plugins:
  - search
  - alternate-link
